feat(SHP-545): Create new address
MOHC-LTD/httpshopify pull request #92
Opened 2022-10-17 09:25 UTC by ezelopes-mohc

2022-10-17 14:39 UTC, Ianmohc requested changes

2022-10-17 14:39 UTC, Ianmohc commented on addresses.go
> -	Address1     string  `json:"address1,omitempty"`
I would leave this one alone where it's always been. Customers have a specific address endpoint so the DTO could be reused from that for standard customer ones.

2022-10-17 14:39 UTC, Ianmohc commented on addresses.go
> -	Address1     string  `json:"address1,omitempty"`
![Screenshot 2022-10-17 at 15 38 28](https://user-images.githubusercontent.com/63408186/196206331-2514755a-b14b-4cfa-88ca-5121619d30e7.png)

2022-10-24 14:10 UTC, rob-mohc commented on customer-address.go
> +	}
What you think of this?

```suggestion
	request := struct {
		CustomerAddressDTO `json:"address"`
	}{
		addressDTO,
	}
```

2022-10-24 14:13 UTC, rob-mohc commented on customer-address.go
> +
And this maybe?

```suggestion
	responseDTO := struct {
		CustomerAddressDTO `json:"customer_address"`
	}{}

	err = json.Unmarshal(resBody, &responseDTO)
	if err != nil {
		return shopify.CustomerAddress{}, err
	}

	return responseDTO.ToShopify(), nil
}

```

2022-10-26 16:00 UTC, rob-mohc approved these changes

2022-10-26 17:02 UTC, merged